### ISSUE TITLE
[BUG]IndexError: tuple assignment index out of range

### ISSUE THREAD

**Issue by medailab** [dashingsoft/pyarmor#1036]
When executing an obfuscated script, the following error occurs.

IndexError: tuple assignment index out of range

In the original script, it is defined with 'tuple(variable) 
The source does not produce any errors when executed

How can I prevent errors from occurring?

----------------------------------------------------------------------------------------------------
--  pyarmor gen
----------------------------------------------------------------------------------------------------
> pyarmor -d gen --prefix prfx -r batch-src -e 2024-03-31 -O C:\WORK\batch
INFO     Python 3.10.9
INFO     Pyarmor 8.0.20 (pro), 005007, MyName
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\MyID\.pyarmor
DEBUG    command options: {'recursive': True, 'output': 'C:\\WORK\\batch', 'no_runtime': False, 'expired': '2024-03-31', 'inputs': ['batch-src'], 'import_prefix': 'prfx'}
INFO     search inputs ...
INFO     find package at batch-src
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write C:\WORK\batch\prfx\pyarmor_runtime_005007\pyarmor_runtime.pyd
INFO     patch runtime file
DEBUG    patching runtime data at 508448
DEBUG    patch runtime file OK
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "batch-src"
INFO     obfuscating file auth_totp.py

----------------------------------------------------------------------------------------------------
--  execute
----------------------------------------------------------------------------------------------------

C:\WORK\batch>python -m foo.py 
Traceback (most recent call last):
  File "C:\uhome\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\uhome\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<C:\WORK\batch\foo.py>", line 3, in <module>
IndexError: tuple assignment index out of range

C:\WORK\batch>>

**Comment by jondy** [comment]
How about remove option `--prefix prfx`?

**Comment by medailab** [comment]
"--prefix prfx" is required.

If this is not present, 
# Pyarmor 8.0.20 (pro), 005007, 2023-03-28T16:53:50.402223
from .pyarmor_runtime_005007 import __pyarmor__
it will not work properly.

If this is not present,
# Pyarmor 8.0.20 (pro), 005007, 2023-03-28T16:53:50.402223
from prfx.pyarmor_runtime_005007 import __pyarmor__
it will work properly.

**Comment by medailab** [comment]
When specifying an individual file, there is certainly no dot. However, when specifying a package, a dot will be included.

**Comment by jondy** [comment]
I don't think so, if no option `-i` and `--prefix`, there is no leading `.` for command `gen`

Could you show me the full command line to obfuscate the package (no `--prefix`)?

**Comment by medailab** [comment]
Thanks, You were right. It seems that a dot was included because the -i option was added before --prefix.

**Comment by jondy** [comment]
It's better to provide a sample script to reproduce this issue.

**Comment by medailab** [comment]
CMD1 : pyarmor gen  -r batch-src -e 2024-03-31 -O C:\WORK\batch-no
CMD2 : pyarmor gen -r -i batch-src -e 2024-03-31 -O C:\WORK\batch-i
CMD3 : pyarmor gen -r --prefix prfx batch-src -e 2024-03-31 -O C:\WORK\batch--prefix
Line2 Result 
CMD1 : from pyarmor_runtime_005007 import __pyarmor__
CMD2 : from .pyarmor_runtime_005007 import __pyarmor__
CMD3 : from prfx.pyarmor_runtime_005007 import __pyarmor__

C:.
│
├─batch--prefix
│  ├─batch-src
│  │      foo.py
│  │
│  └─prfx
│      └─pyarmor_runtime_005007
│              pyarmor_runtime.pyd
│              __init__.py
│
├─batch-i
│  └─batch-src
│          foo.py
│
├─batch-no
│  ├─batch-src
│  │      foo.py
│  │
│  └─pyarmor_runtime_005007
│          pyarmor_runtime.pyd
│          __init__.py
│
└─batch-src
        foo.py
[WORK.zip](https://github.com/dashingsoft/pyarmor/files/11089278/WORK.zip)

**Comment by medailab** [comment]
I've tried it with CMD1 but still haven't solved it.
-----------------------------------------------------------------
C:\nginx>CD C:\APP\batch\batch

C:\APP\batch\batch>python -m MyStartupMain   -j 2 -r 2
Traceback (most recent call last):
  File "C:\uhome\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\uhome\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
IndexError: tuple assignment index out of range

C:\APP\batch\batch>

**Comment by kr1tx** [comment]
I have the same issue. 
Command used: `pyarmor -d gen foo.py`

```
Traceback (most recent call last):
  File "<C:\src\foo.py>", line 3, in <module>
IndexError: tuple assignment index out of range
```

**Comment by jondy** [comment]
@kr1tx could you share a simple `foo.py`? And which Python version is used.

**Comment by fO-000** [comment]
Encountered the same error in:

* Python 3.11.2
* pyarmor 8.0.21 (basic)
* pyarmor.cli.core 1.0.10
* OS: VMware guest `Linux x 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1kali1 (2023-03-22) x86_64 GNU/Linux`

**Comment by kr1tx** [comment]
@jondy  , I apologize I cannot share a sample of my script. I attempted to remove many lines and started obfuscating the script to identify the cause of the problem. I discovered that if I removed a single line from a particular dictionary, the problem disappears . This is all I have.

```
self.listOfMagic = {
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
    'key': 'key',
} 
```

**Comment by fO-000** [comment]
Hi @jondy, Here is what I found. 

I have a py script that defines many classes. If **> 57** classes are defined, it will report an `IndexError: tuple assignment index out of range` when executed after it is obfuscated. And If the defined classes **<= 57** then there is no problem.

**Comment by jondy** [comment]
@fO-000 @kr1tx Thank you very much.

Next I may stop urgent release, and do a full test for next minor release 8.1

All of these bugs should be fixed in next minor release.

**Comment by kr1tx** [comment]
@jondy  error still persists for me.

**Comment by jondy** [comment]
@kr1tx  make sure pyarmor.cli.core == 1.0.12

**Comment by fO-000** [comment]
@jondy Glad to help

And the pyarmor is still 8.0.22 in [PyPI](https://pypi.org/project/pyarmor/), not 8.0.25.

**Comment by jondy** [comment]
Sorry, I forget to upload to PyPI. Try it now.

**Comment by jondy** [comment]
In dev version `8.1.dev1`, I also fixed another `tuple index out of range` bug.

**Comment by kr1tx** [comment]
@jondy  it was `pyarmor.cli.core == 1.0.12` , now upgraded it to `1.0.15` and another error occurred.  
Command used: `pyarmor gen vSender.py`
```
16204 MainProcess 2023-04-01
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 585, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 573, in main_entry
    args.func(ctx, args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 152, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\generate.py", line 149, in process
    self.generate_runtime_package(self.ctx.outputs[0])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\generate.py", line 88, in generate_runtime_package
    Pytransform3.generate_runtime_package(self.ctx, output)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\core\__init__.py", line 53, in generate_runtime_package
    return m.generate_runtime_package(ctx, output, platforms)
  File "<maker>", line 725, in generate_runtime_package
  File "<maker>", line 409, in build
AttributeError: 'Context' object has no attribute 'target_platforms'

```

**Comment by kr1tx** [comment]
@jondy  it was pyarmor.cli.core==1.0.12 upgraded it to 1.0.15 and error still persists for me.
```
INFO     Python 3.10.8
INFO     Pyarmor 8.0.26 (pro)
```

**Comment by jondy** [comment]
The fixed version is dev version `8.1.dev` with core `1.0.16a1`, I need do a full test in a week, then release minor version `8.1`

**Comment by wsxhd7881** [comment]
8.1.dev4也遇到了这个问题，等待新版本解决

**Comment by jondy** [comment]
trace this issue #1096
