### ISSUE TITLE
[BUG] `pyarmor cfg on_error do not work`

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#1157]
How to reproduce:
1st command: `pyarmor cfg on_error=2`
2nd command: `pyarmor gen  -e 2020-05-01 Script.py`
3rd command: `dist\Script.py`

I created a file called `messages.cfg` within the .pyarmor folder and added the following into it *as I read from the pyarmor 8.0 doc.
Also tried using `pyarmor cfg on_error=1` to only display the error message and `pyarmor cfg on_error=2` to not show any error msg at all but they did not work.
```
[runtime.message]
error_1 = ErrorMSG: License has expired
```
So the problem is that I don't want this ugly message to be shown when the license is expired, instead i want only `ErrorMSG: License has expired` to be shown.
```
Traceback (most recent call last):
  File "dist\Script.py", line 2, in <module>
    from pyarmor_runtime_xxxxxx import __pyarmor__
  File "dist\pyarmor_runtime_xxxxxx\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: ErrorMSG: License has expired (1:10937)
```

**Comment by jondy** [comment]
Reproduced, it will be fixed in next release.

**Comment by jondy** [comment]
It works by this way:
```
pyarmor cfg runtime:on_error=1
```

**Comment by kr1tx** [comment]
You are right `pyarmor cfg runtime:on_error=1` works! If it exists in the doc. I apologize for not paying close attention.

**Comment by jondy** [comment]
Sorry, it's not in the documentation now.  `pyarmor cfg on_error` is a short form but there is a bug on this short form, I have fixed this in next released.

**Comment by kr1tx** [comment]
i can still see a runtime error now after setting `pyarmor cfg runtime:on_error=2` any alternative solution?

**Comment by jondy** [comment]
This only works for Pyarmor self errors, for example, license expired etc.

If python script raises exception, it doesn't work.

**Comment by jondy** [comment]
About this question please consult Python documentation, understand Python how to deal with keypress `ctrl-c`
