### ISSUE TITLE
[BUG] `Error message "request license token failed (3): 214" while running pyarmor register on linux`

### ISSUE THREAD

**Issue by shahir-imemori** [dashingsoft/pyarmor#1582]
We are having pyarmor pro license for iMemori Technologies. Trying to run the obfuscator on linux machine.  Pyarmor version is pyarmor-8.4.3

On my local mac environment it is working. Checked for the internet connection on linux and found no problem. Following are the details
```
 > [imem-api 14/18] RUN pyarmor -d reg pyarmor/pyarmor-regfile-5397.zip:                                                                      
#0 1.060 INFO     Python 3.10.13                                                                                                              
#0 1.060 INFO     Pyarmor 8.4.3 (trial), 000000, non-profits                                                                                  
#0 1.061 INFO     Platform linux.x86_64                                                                                                       
#0 1.061 DEBUG    native platform linux.x86_64                                                                                                
#0 1.061 DEBUG    home path: /app/.pyarmor
#0 1.061 INFO     register "pyarmor/pyarmor-regfile-5397.zip"
#0 1.063 DEBUG    extracting license.lic
#0 1.063 DEBUG    extracting .pyarmor_capsule.zip
#0 1.064 INFO     update license token
#0 1.629 DEBUG    unknown error, please check pyarmor.error.log
#0 1.630 ERROR    request license token failed (3): 214
#0 1.630 OK:9jkAAAEHAAADJ1JlAAAAAHB5YXJtb3ItdmF4LTAw.......
#0 1.630 0
#0 1.630 
#0 1.630 

```

cat pyarmor.error.log 
3392791 MainProcess 2023-11-10 20:17:36,426
Traceback (most recent call last):
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 718, in main
    main_entry(sys.argv[1:])
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 706, in main_entry
    return args.func(ctx, args)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 305, in cmd_reg
    reg.register_regfile(regfile)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 209, in register_regfile
    self.update_token()
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 116, in update_token
    Pytransform3._update_token(self.ctx)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/core/__init__.py", line 127, in _update_token
    m = Pytransform3.init(ctx)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/pyarmor/cli/core/__init__.py", line 97, in init
    m.init_ctx(ctx)
RuntimeError: request license token failed (3): 214
OK:AjoAAAEHAAAHN1JlAAAAAHB5YXJtb3ItdmF4LTAwNTM5NwAApZfUzn6enzgZVx...
0

 ~/.local/bin/pyarmor gen -O dist -r src/*
INFO     Python 3.10.12
INFO     Pyarmor 8.4.3 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find package at src/db
INFO     find script src/main.py
INFO     find package at src/models
INFO     find package at src/processor
INFO     find package at src/router
INFO     find package at src/util
INFO     find 6 top resources
ERROR    request license token failed (3): 214
OK:BDoAAAEHAAAtOlJlAAAAAHB5YXJtb3ItdmF4LTAwNTM5NwAApZfUzn6enzgZVxuwdkIJZAAAAAAAAAAAAAAAACFiZDFhZjY4MmMzZjY2Nzc3OGI1ZjI3MDZiODhiMDQwNjUcaU1lbW9yaSBU...0Gw==
0

**Comment by jondy** [comment]
I fix one request token issue if there is proxy, try it by downloading temporary extension
https://pyarmor.dashingsoft.com/downloads/temp/5.4.2/linux.x86_64/libs/cp3.10/pytransform3.so

And overwrite `/path/to/pyarmor/cli/core/pytransform3.so`

**Comment by shahir-imemori** [comment]
I do not have proxy. However, I tried replacing the pytransform3.so used by the pyarmor. I am still getting the same error

**Comment by jondy** [comment]
What's the full log of 
```
pyarmor -d reg pyarmor/pyarmor-regfile-5397.zip
```

**Comment by jondy** [comment]
It seems the response from pyarmor license server has been changed by some middle router or server. If you know how to track http response from host `pyarmor.dashingsoft.com`, please report the raw response, it should be like
```
    HTTP/1.1 200 OK
    Date: Fri, 05 Mar 2021 15:39:26 GMT
    Server: WSGIServer/0.2 CPython/3.5.2
    Allow: OPTIONS, GET
    X-Frame-Options: SAMEORIGIN
    Content-Type: text/html; charset=utf-8
    Content-Length: 8
    Vary: Accept, Cookie
    \r\n
    OK:xxxxxxxx
```

If you don't know how to check this, I'll build a temporary extension to print this response when I'm back (now I'm out of office).

**Comment by shahir-imemori** [comment]
Hi Jondy,

Between the build server and pyarmor we only have Azure firewall.

I do not know how to get the raw response as I am not aware what is the HTTP request pyarmor is sending to the server. Please help to share the relevant details so that I can do curl request to send and share the details.

--
Cheers,
Mohamed Shahir


From: Jondy ***@***.***>
Date: Tuesday, 14 November 2023 at 6:28 PM
To: dashingsoft/pyarmor ***@***.***>
Cc: Mohamed Shahir ***@***.***>, Author ***@***.***>
Subject: Re: [dashingsoft/pyarmor] [BUG] `Error message "request license token failed (3): 214" while running pyarmor register on linux` (Issue #1582)

It seems the response from pyarmor license server has been changed by some middle router or server. If you know how to track http response from host pyarmor.dashingsoft.com, please report the raw response, it should be like

    HTTP/1.1 200 OK

    Date: Fri, 05 Mar 2021 15:39:26 GMT

    Server: WSGIServer/0.2 CPython/3.5.2

    Allow: OPTIONS, GET

    X-Frame-Options: SAMEORIGIN

    Content-Type: text/html; charset=utf-8

    Content-Length: 8

    Vary: Accept, Cookie

    \r\n

    OK:xxxxxxxx

If you don't know how to check this, I'll build a temporary extension to print this response when I'm back (now I'm out of office).

**Comment by jondy** [comment]
I add test api, please report the full output of this command 
```
curl -v -k https://api.dashingsoft.com/product/key/test
```

**Comment by shahir-imemori** [comment]
Please find below response for the command executed

curl -v -k https://api.dashingsoft.com/product/key/test
*   Trying 119.23.58.77:443...
* Connected to api.dashingsoft.com (119.23.58.77) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.dashingsoft.com
*  start date: Oct 29 20:06:56 2023 GMT
*  expire date: Jan 27 20:06:55 2024 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /product/key/test HTTP/1.1
> Host: api.dashingsoft.com
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Wed, 15 Nov 2023 04:29:46 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 360
< Connection: keep-alive
< Vary: Accept, Cookie
< Allow: GET, OPTIONS
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT
<
* Connection #0 to host api.dashingsoft.com left intact
OK:YWJjZGVmZw== Zt6AQLgBaX+ifwfdTdAEuSp2J6rut65T7Nvd8S+ydra83/E5hi4MZ0zTR5aHuHpR1i4L9K0NR/cqbScdL2usEoOlDNi60Km2fHyWYzVnCIiaQvFbsXoECN0COZt8SD8gH2RoyHJ3rqimE3FrwIyF6bu3HTjlHKgZtUKiOskqxwHxEu2K5VaVljcMeln2mAMpQg5Jbs7hqVn6IV4WYGbBkeUJp1d7YCF60QHGHITMJ5MtSnlXFpxwydU86tPg18nxuRBk6KY5aUo+HG+2Z3JkvS+FZakgySEXL9HhyVbEOp/PtH/B0O+utGKPdz3DDfAIVB6Pgsd/vDXqyErEUT++vw==

--
Cheers,
Mohamed Shahir


From: Jondy ***@***.***>
Date: Wednesday, 15 November 2023 at 8:44 AM
To: dashingsoft/pyarmor ***@***.***>
Cc: Mohamed Shahir ***@***.***>, Author ***@***.***>
Subject: Re: [dashingsoft/pyarmor] [BUG] `Error message "request license token failed (3): 214" while running pyarmor register on linux` (Issue #1582)

I add test api, please report the full output of this command

curl -v -k https://api.dashingsoft.com/product/key/test

**Comment by jondy** [comment]
What's the response of http?
```
curl -v http://api.dashingsoft.com/product/key/test 
```

**Comment by jondy** [comment]
I uploaded new one, try it by downloading temporary extension                                    
https://pyarmor.dashingsoft.com/downloads/temp/5.4.2/linux.x86_64/libs/cp3.10/pytransform3.so 

And overwrite `/path/to/pyarmor/cli/core/pytransform3.so`

**Comment by shahir-imemori** [comment]
With the new library file, I am able to get it working. Will there be new version with the above fix?

**Comment by jondy** [comment]
The new version will be released at the beginning of next month, please watch the release in this repo.

**Comment by jondy** [comment]
Fixed in v8.4.4

**Comment by shahir-imemori** [comment]
I upgraded pyarmor and tested the version. I am getting below error.

pyarmor reg pyarmor/pyarmor-regfile-5397.zip:
8.205 INFO     Python 3.10.13
8.206 INFO     Pyarmor 8.4.4 (trial), 000000, non-profits
8.210 INFO     Platform linux.x86_64
8.214 INFO     register "pyarmor/pyarmor-regfile-5397.zip"
8.247 INFO     update license token
9.678 ERROR    request license token failed (3): <h1>Server Error (500)</h1>

**Comment by shahir-imemori** [comment]
@jondy , I am still having problems with the registration on version 8.4.4 on my Linux build environment

#121 [imem_xxxxx imem-xxxxx 12/16] RUN pyarmor -d reg pyarmor/pyarmor-regfile-5397.zip
#121 2.575 INFO     Python 3.10.13
#121 2.576 INFO     Pyarmor 8.4.4 (trial), 000000, non-profits
#121 2.577 INFO     Platform linux.x86_64
#121 2.577 DEBUG    native platform linux.x86_64
#121 2.577 DEBUG    home path: /app/.pyarmor
#121 2.577 INFO     register "pyarmor/pyarmor-regfile-5397.zip"
#121 2.581 DEBUG    extracting license.lic
#121 2.581 DEBUG    extracting .pyarmor_capsule.zip
#121 2.582 INFO     update license token
#121 3.370 DEBUG    unknown error, please check pyarmor.error.log
#121 3.372 ERROR    invalid license token, try to run `pyarmor reg` to register license again
#121 ERROR: process "/bin/sh -c pyarmor -d reg pyarmor/pyarmor-regfile-5397.zip" did not complete successfully: exit code: 2

**Comment by jondy** [comment]
In 24 hours, only 100 devices are available for one license, there are more than 100 devices are used for this license.

Please report new issue, do not comment to closed issue
