### ISSUE TITLE
[BUG] Cant build onefile executable

### ISSUE THREAD

**Issue by RobertAzovski** [dashingsoft/pyarmor#1745]
Trying to pack file to one executable:

```
$ pyarmor -d gen --pack onefile myUiExample.py
INFO     Python 3.11.4
INFO     Pyarmor 8.5.4 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\User\.pyarmor
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
DEBUG    command options: {'no_runtime': False, 'inputs': ['myUiExample.py'], 'output': '.pyarmor\\pack\\dist'}
DEBUG    install plugin: CodesignPlugin
DEBUG    install plugin: DarwinUniversalPlugin
DEBUG    Loaded ctypes backend
INFO     search inputs ...
INFO     find script myUiExample.py
INFO     find 1 top resources
Wrote .pyarmor\pack\myUiExample.spec.
Now run pyinstaller.py to build the executable.
314 INFO: PyInstaller: 6.6.0, contrib hooks: 2024.4
314 INFO: Python: 3.11.4
328 INFO: Platform: Windows-10-10.0.19045-SP0
option(s) not allowed:
  --onedir/--onefile
makespec options not valid when a .spec file is given
DEBUG    unknown error, please check pyarmor.error.log
ERROR    Command '['C:\\Dev\\sssr\\venv\\Scripts\\python.exe', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor\\pack\\build', '-F', '.pyarmor\\pack\\myUiExample.spec']' returned non-zero exit status 1.
ERROR    somthing is wrong
*=============================================================*
*  Please check                                               *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*                                                             *
*  It's recommand to report issue by `pyarmor man` in order   *
*  to provide necessary information, and avoid dupcliated     *
*  issues or unclear question.                                *
*=============================================================*
```

**Comment by RobertAzovski** [comment]
pyarmor.debug.log:
```
2024-04-23 00:57:36,785 Python 3.11.4
2024-04-23 00:57:36,785 Pyarmor 8.5.4 (trial), 000000, non-profits
2024-04-23 00:57:36,786 Platform windows.x86_64
2024-04-23 00:57:36,786 native platform windows.amd64
2024-04-23 00:57:36,787 home path: C:\Users\User\.pyarmor
2024-04-23 00:57:36,787 implicitly save obfuscated scripts to ".pyarmor\pack\dist"
2024-04-23 00:57:36,787 command options: {'no_runtime': False, 'inputs': ['myUiExample.py'], 'output': '.pyarmor\\pack\\dist'}
2024-04-23 00:57:36,788 install plugin: CodesignPlugin
2024-04-23 00:57:36,788 install plugin: DarwinUniversalPlugin
2024-04-23 00:57:36,832 Loaded ctypes backend
2024-04-23 00:57:36,884 search inputs ...
2024-04-23 00:57:36,885 find script myUiExample.py
2024-04-23 00:57:36,885 find 1 top resources
2024-04-23 00:57:37,745 unknown error, please check pyarmor.error.log
2024-04-23 00:57:37,751 Command '['C:\\Dev\\gmc-sender\\venv\\Scripts\\python.exe', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor\\pack\\build', '-F', '.pyarmor\\pack\\myUiExample.spec']' returned non-zero exit status 1.
2024-04-23 00:57:37,763 somthing is wrong
*=============================================================*
*  Please check                                               *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*                                                             *
*  It's recommand to report issue by `pyarmor man` in order   *
*  to provide necessary information, and avoid dupcliated     *
*  issues or unclear question.                                *
*=============================================================*
```

**Comment by RobertAzovski** [comment]
### Traceback
Traceback (most recent call last):
  File "C:\Dev\sssr\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 768, in main
    main_entry(sys.argv[1:])
  File "C:\Dev\sssr\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 756, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\sssr\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 238, in cmd_gen
    builder.process(options, packer)
  File "C:\Dev\sssr\venv\Lib\site-packages\pyarmor\cli\generate.py", line 163, in process
    auto_resources = packer.analysis()
                     ^^^^^^^^^^^^^^^^^
  File "C:\Dev\sssr\venv\Lib\site-packages\pyarmor\cli\repack.py", line 555, in analysis
    check_call(cmdlist)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Dev\\sssr\\venv\\Scripts\\python.exe', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor\\pack\\build', '-F', '.pyarmor\\pack\\myUiExample.spec']' returned non-zero exit status 1.

**Comment by jondy** [comment]
Apply this patch to fix it
```patch
--- a/pyarmor/cli/repack.py
+++ b/pyarmor/cli/repack.py
@@ -539,7 +539,9 @@ class Repacker6:
             sys.executable, '-m', 'PyInstaller.utils.cliutils.makespec',
             '--specpath', self.packpath
         ]
-        cmdspec.extend(self.filter_opts(self.pyiopts, ('--name', '-N')))
+        exvalues = '--name', '-N'
+        exopts = '-F', '--onefile', '-D', '--onefolder'
+        cmdspec.extend(self.filter_opts(self.pyiopts, exvalues, exopts))
         cmdspec.append(self.script)
         logger.debug('%s', ' '.join(cmdspec))
         logger.info('call PyInstaller to generate specfile')
```
It will be fixed in next release v8.5.6

**Comment by jondy** [comment]
Here it's pre-release version
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.5.6.zip

**Comment by RobertAzovski** [comment]
Thx. But now facing new issue. Seems like pyarmor tries to obfuscate whole my VENV(virtual invironment) and a license limit gets reached.

```
$ pyarmor gen --pack onefile myUiExample.py
INFO     Python 3.11.4
INFO     Pyarmor 8.5.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
INFO     search inputs ...
INFO     find script myUiExample.py
INFO     find 1 top resources
INFO     call PyInstaller to generate specfile
INFO     call PyInstaller to analysis, it may take several minutes ...
INFO     find extra resources: ['venv\\Lib\\site-packages\\socks.py', 'venv']
INFO     find script venv\Lib\site-packages\socks.py
INFO     find package at venv
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write .pyarmor\pack\dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "myUiExample"
INFO     obfuscating file myUiExample.py
INFO     write .pyarmor\pack\dist\myUiExample.py
INFO     process resource "socks"
INFO     obfuscating file socks.py
INFO     write .pyarmor\pack\dist\socks.py
INFO     process resource "venv"
INFO     obfuscating file pefile.py
ERROR    out of license
ERROR    somthing is wrong
*=============================================================*
*  Please enable debug option `-d` to run it again            *
*    pyarmor -d gen options ...                               *
*                                                             *
*  Then check console log to find more information            *
*                                                             *
*  Please also check                                          *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*=============================================================*
```

But if I do simple `pyarmor gen -O dist myUiExample.py`, there is no such issue.

I tried also to use `--exclude flag` but still pyarmor tries to obfuscate all dependancies in venv folder.
`pyarmor gen --exclude "./venv/" --pack onefile myUiExample.py`

**Comment by jondy** [comment]
What's the output in the venv?
```
python
>>> from PyInstaller.compat import base_prefix
>>> print(base_prefix)
```

**Comment by jondy** [comment]
And try exclude `venv` by this way
```
pyarmor gen --exclude "*/venv" ...
```

**Comment by jondy** [comment]
Sorry, fixed in this pre-release version                           
                                                                     
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.5.7.zip

**Comment by RobertAzovski** [comment]
Tried this way, the same `pyarmor gen --exclude "*/venv" --pack onefile myUiExample.py`

Ok. Thanks. I will try this new version today.

**Comment by jondy** [comment]
Sorry, it's better to wait for new release v8.5.7.

I think it need more tests before publish.

**Comment by RobertAzovski** [comment]
Ok, thanks a lot. We are all grateful for your support. Taking this opportunity to also mention that `out of license` ERROR also raises when I use any of these flags --enable-bcc--enable-themida --mix-str with `pyarmor gen`

**Comment by jondy** [comment]
Some features like `--enable-bcc` are not available in the trial version, do not use these features in trial version.

I also fix a few bugs for pack and upload pre-release v8.5.7 at same location, you can check it in any free time.

**Comment by jondy** [comment]
Fixed in 8.5.7

**Comment by RobertAzovski** [comment]
Thanks. This is building exe know. But final exe got 27 mb instead 40 mb before and got this error.
![image](https://github.com/dashingsoft/pyarmor/assets/111636889/994cf419-0cc9-4952-9b71-2be6f6d1fe13)

**Comment by RobertAzovski** [comment]
`pyarmor gen --exclude "./venv" --pack onefile myUiExample.py` this is what I used

**Comment by jondy** [comment]
The problem is that pyarmor ignore extensions, it will be fixed in next version.

A quick workaround is to add one hidden import, for example

```
pyarmor cfg pack:pyi_options = "--hidden-import PyQt5.QtWidgets"
pyarmor gen --pack onefile ...
```

**Comment by jondy** [comment]
Fixed in 8.5.8

**Comment by RobertAzovski** [comment]
Ok then i will try it thx

**Comment by RobertAzovski** [comment]
Seems like problem is still exists if we use `--pack` flag on pyintaller built executable:
`pyarmor gen --pack dist/_tg.exe _tg.py
INFO     Python 3.11.9
INFO     Pyarmor 8.5.8 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
INFO     extracting bundle "dist/my_file.exe"
INFO     search inputs ...
INFO     find script my_file.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write .pyarmor\pack\dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "my_file"
INFO     obfuscating file my_file.py
INFO     write .pyarmor\pack\dist\my_file.py
INFO     obfuscate scripts OK
INFO     repacking bundle "dist/my_file.exe"
INFO     obfuscated scripts at "dist"
INFO     entry script name is "my_file.py"
INFO     repacking "PYZ-00.pyz"
ERROR    [Errno 2] No such file or directory: '.pyarmor\\pack\\PYZ-00.pyz_extracted\\pyarmor_runtime_000000\\__init__.pyc'
ERROR    something is wrong
*=============================================================*
*  Please enable debug option `-d` to run it again            *
*    pyarmor -d gen options ...                               *
*                                                             *
*  Then check console log to find more information            *
*                                                             *
*  Please also check                                          *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*=============================================================*`

**Comment by jondy** [comment]
duplicated #1764
